### PR TITLE
Support for TeamCity managing Unity as a tool

### LINKED ISSUE #35: Unity Tool install isn't triggered and build is blocked by path variable usage
If you install Unity as a TeamCity tool using the instructions provided by JetBrains and linked in the Readme, the build that references that new version will be blocked indefinitely as the tool is not triggered to install by the build and the `unity.path.<version>` Configuration Parameter causes the build to not find compatible agents as the Tool not only needs to be installed, but also needs to trigger the Unity Runner Plugin to re-search for Unity installations to populate this field.

So I see 2 related but distinct issues here:
1. Runner doesn't inform TeamCity to install the Tool
2. Once tool is installed, a restart of the agent is required as the Unity Runner doesn't update its path variables as a response to a tool install

My repro case:
1. Already have a licensed Unity install on the Agent
2. Create a new tool for a new Unity version (2018.4.6) using the documentation here: [Installing Agent Tools](https://www.jetbrains.com/help/teamcity/installing-agent-tools.html) and here: [Plugins Packaging](https://plugins.jetbrains.com/docs/teamcity/plugins-packaging.html?_ga=2.54199912.112789028.1565708271-1432284306.1556119626#Tools)
3. Install new Tool using TeamCity Administration page
4. Create a new build configuration with the Unity Runner and set the version to this new tool

**Expected**: Build runs, triggering tool install on agent that does not yet have that tool
**Actual**: Build is blocked indefinitely as `unity.path.2018.4.6` is not defined and the build will not run to install the tool.

### PR DESCRIPTION
**Pull request by AaronZurawski**
Installing Unity as a TeamCity tool using the Zip archive "tool" was supported and worked mildly well. However, there were several issues with this approach:

1. Version management was based completely on names/vars
1. Using the path variables meant that the agent needed to be restarted (See #35 )
1. Selection of versions was not user friendly
1. No easy way to specify/alter default version

To resolve these issues, I introduced support for a Unity Tool Provider. I made sure to still allow for the previous methods for installing Unity and the default option remains the same. Support was added to both Build Feature and Build Runner.

Fixes #35 

image
image
image

### CODE REVIEW

**Comment by twomedia** [comment]
This should really be merged. We've been using this on our TeamCity instance for over 6 months & it works great. This is how the plugin should've been made from the start.

**Review by lesley29 — CHANGES_REQUESTED** [review]
Thank you very much for your contribution @AaronZurawski, great job!
Could you please do a rebase on the "master"? I also left a couple of minor comments. Please check them out as well.

Sorry for such a long delay with the response and review. We are now back to support and development of the plugin.

**Review by lesley29 — APPROVED** [review]

**Review by mchechulnikov — APPROVED** [review]

**Comment by AaronZurawski** [comment]
@lesley29 Sorry for missing these notifications - I recently changed jobs and haven't had much time to work on other projects. Thanks for getting this merged!

**Comment by lesley29** [comment]
Hi, @AaronZurawski 

No problem at all! We understand how busy life can get, especially with a new job. We appreciate your contribution and you are always welcome to participate in the future.

Also, could you please sign the "JetBrains Contributor License Agreement (CLA)" form [here](https://www.jetbrains.com/agreements/cla/) (there are just 3 lines). Thank you again for your valuable input!

**Pull request merged**
